name: Generate Snake Grid

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate Custom Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Difarias
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?color_snake=#BD00FF&color_dots=#161b22,#003311,#008833,#00e65c,#00ff66

      - name: Push Snake SVG to Output Branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
